---
- name: Automate Zabbix Agent Deployment
  hosts: all
  become: yes
  vars:
    zabbix_server_ip: "192.168.28.10" # Control 节点的 IP
  tasks:
    - name: 1. Install Zabbix Release Repo
      dnf:
        name: https://repo.zabbix.com/zabbix/7.0/rhel/8/x86_64/zabbix-release-7.0-2.el8.noarch.rpm
        state: present
        disable_gpg_check: yes

    - name: 2. Install Zabbix Agent
      dnf:
        name: zabbix-agent
        state: present

    - name: 3. Configure Zabbix Server IP
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: "Server={{ zabbix_server_ip }}"

    - name: 4. Configure ServerActive IP
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: "ServerActive={{ zabbix_server_ip }}"

    - name: 5. Set Hostname (Using Ansible Inventory Name)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: "Hostname={{ inventory_hostname }}"

    - name: 6. Start and Enable Agent
      service:
        name: zabbix-agent
        state: restarted
        enabled: yes

    - name: 7. Open Firewall Port 10050
      firewalld:
        port: 10050/tcp
        permanent: yes
        state: enabled
        immediate: yes
      ignore_errors: yes
