---
- name: Deploy Zabbix Monitoring
  hosts: all
  become: yes

  tasks:
    - name: 1. Install EPEL and Zabbix Repository
      dnf:
        name:
          - epel-release
          - https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-1.el8.noarch.rpm
        state: present

    - name: 2. Import Zabbix GPG Key
      rpm_key:
        key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
        state: present

    - name: 3. Configure Database for Zabbix (on db node)
      when: inventory_hostname in groups['db']
      block:
        - name: Create Zabbix Database
          community.mysql.mysql_db:
            name: zabbix
            state: present
            login_user: root
            login_password: "Lsp100487"

        - name: Create Zabbix DB User
          community.mysql.mysql_user:
            name: zabbix
            password: "zabbix_pass"
            priv: "zabbix.*:ALL"
            host: "%"
            login_user: root
            login_password: "Lsp100487"

    - name: 4. Install Zabbix Server (on db node)
      when: inventory_hostname in groups['db']
      dnf:
        name: zabbix-server-mysql
        state: present

    - name: 5. Import Zabbix Initial Schema
      when: inventory_hostname in groups['db']
      command: zcat /usr/share/doc/zabbix-server-mysql/create.sql.gz | mysql -uzabbix -pzabbix_pass zabbix
      args:
        warn: no

    - name: 6. Configure Zabbix Server
      when: inventory_hostname in groups['db']
      template:
        src: zabbix_server.conf.j2
        dest: /etc/zabbix/zabbix_server.conf
      notify: restart zabbix-server

    - name: 7. Start Zabbix Server
      when: inventory_hostname in groups['db']
      service:
        name: zabbix-server
        state: started
        enabled: yes

    - name: 8. Install Zabbix Agent on Web Nodes
      when: inventory_hostname in groups['web']
      dnf:
        name: zabbix-agent
        state: present

    - name: 9. Configure Zabbix Agent
      when: inventory_hostname in groups['web']
      template:
        src: zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
      notify: restart zabbix-agent

    - name: 10. Start Zabbix Agent
      when: inventory_hostname in groups['web']
      service:
        name: zabbix-agent
        state: started
        enabled: yes

    - name: 11. Configure Firewall
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - http
        - zabbix-agent
      ignore_errors: yes

  handlers:
    - name: restart zabbix-server
      service:
        name: zabbix-server
        state: restarted

    - name: restart zabbix-agent
      service:
        name: zabbix-agent
        state: restarted

