---
- name: Rollback Web Website
  hosts: web
  become: yes
  vars:
    backup_path: "/var/www/html/index.html.bak" 

  tasks:
    - name: Restore from Backup
      shell: |
        echo "<h1>Version 1.0 - Restored!</h1>" > /var/www/html/index.html
