---
- name: Rolling Update Web Servers
  hosts: web
  serial: 1  
  become: yes

  tasks:
    - name: 1. Stop Web Service (模拟从负载均衡摘除)
      service:
        name: httpd
        state: stopped

    - name: 2. Update Website Content (模拟更新)
      shell: echo "<h1>Version 2.0 - Update Success! Server {{ inventory_hostname }}</h1>" > /var/www/html/index.html

    - name: 3. Restart Web Service
      service:
        name: httpd
        state: started

    - name: 4. Wait for Server to come back
      wait_for:
        port: 80
        delay: 5
